version: '3.9'

services:
 postgres:
  image: postgres:latest
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: phonebook
  ports:
   - "5432:5432"
  volumes:
   - postgres:/data/postgres
   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  restart: always

volumes:
 postgres: